# Generated by Django 4.2.30 on 2026-06-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricanteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre', models.CharField(max_length=150)),
                ('num_telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Fabricante de Medicamento',
                'verbose_name_plural': 'Fabricantes de Medicamentos',
                'db_table': 'FABRICANTES_MEDICAMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=100)),
                ('num_ext', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=100)),
                ('estado_ciudad', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
                'db_table': 'FARMACIAS',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'INVENTARIOS',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre_generico', models.CharField(max_length=150)),
                ('nombre_comercial', models.CharField(blank=True, max_length=150, null=True)),
                ('contenido_neto', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medicamentos', to='inventario.fabricantemedicamento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'MEDICAMENTOS',
            },
        ),
    ]
