services:
  # ========================================================================
  # SERVICIO 1: MARIADB
  # ========================================================================
  db:
    image: mariadb:10.11
    container_name: mariadb_clinica
    restart: always
    env_file:
      - .env
    #ports:
    #  - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      # - ./db_scripts:/docker-entrypoint-initdb.d
    networks:
      - red_cliniccontrol

  # ========================================================================
  # SERVICIO 2: ACTIVEMQ
  # ========================================================================
  activemq:
    image: rmohr/activemq:latest
    container_name: broker_mensajeria
    restart: always
    ports:
      #- "61613:61613" # Puerto oficial para STOMP TCP
      - "61614:61614" # Puerto para STOMP sobre WebSocket
      #- "8161:8161"   # Panel de administración web de ActiveMQ
    volumes:
      - ./config/activemq/users.properties:/opt/activemq/conf/users.properties:ro
      - ./config/activemq/groups.properties:/opt/activemq/conf/groups.properties:ro
    networks:
      - red_cliniccontrol

  # ========================================================================
  # SERVICIO 3: SERVIDOR DE APLICACIÓN WEB (DJANGO - CLINICCONTROL)
  # ========================================================================
  web:
    build: .
    container_name: django_cliniccontrol
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - activemq
    networks:
      - red_cliniccontrol

# ==========================================================================
# VOLÚMENES Y REDES (PERSISTENCIA Y AISLAMIENTO)
# ==========================================================================
volumes:
  # El volumen físico en la máquina anfitriona asegura las propiedades ACID (Durabilidad)
  mariadb_data:

networks:
  # Aísla la comunicación interna de los contenedores por seguridad
  red_cliniccontrol:
    driver: bridge
