services:
  # ========================================================================
  # SERVICIO 1: MOTOR DE BASE DE DATOS RELACIONAL (MARIADB)
  # ========================================================================
  db:
    image: mariadb:10.11
    container_name: mariadb_clinica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_secreta
      MYSQL_DATABASE: clinica_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      # Opcional: Descomenta la siguiente línea si quieres que tus scripts SQL 
      # se ejecuten automáticamente la primera vez que se cree el contenedor.
      # - ./db_scripts:/docker-entrypoint-initdb.d
    networks:
      - red_clinica

  # ========================================================================
  # SERVICIO 2: BROKER DE MENSAJERÍA EN TIEMPO REAL (ACTIVEMQ)
  # ========================================================================
  activemq:
    image: rmohr/activemq:latest
    container_name: broker_mensajeria
    restart: always
    ports:
      - "61613:61613" # Puerto oficial para STOMP TCP
      - "61614:61614" # Puerto para STOMP sobre WebSocket
      - "8161:8161"   # Panel de administración web de ActiveMQ
    networks:
      - red_clinica

  # ========================================================================
  # SERVICIO 3: SERVIDOR DE APLICACIÓN WEB (DJANGO - CLINICCONTROL)
  # ========================================================================
  web:
    build: .
    container_name: django_cliniccontrol
    restart: always
    ports:
      - "8000:8000"
    # Enlaza el archivo de configuración para inyectar las credenciales de forma segura
    env_file:
      - .env
    # Garantiza el orden de encendido de la arquitectura distribuida
    depends_on:
      - db
      - activemq
    networks:
      - red_clinica

# ==========================================================================
# VOLÚMENES Y REDES (PERSISTENCIA Y AISLAMIENTO)
# ==========================================================================
volumes:
  # El volumen físico en la máquina anfitriona asegura las propiedades ACID (Durabilidad)
  mariadb_data:

networks:
  # Aísla la comunicación interna de los contenedores por seguridad
  red_clinica:
    driver: bridge
