USE clinica_db;

-- Desactivar validacion de llaves foráneas para evitar conflictos
SET FOREIGN_KEY_CHECKS = 0;

-- Destrucción atómica y limpia de todas las tablas si existen
DROP TABLE IF EXISTS MENSAJES;
DROP TABLE IF EXISTS SALAS_CHAT;
DROP TABLE IF EXISTS SOLICITUDES_ESTUDIO;
DROP TABLE IF EXISTS RECETA_MEDICAMENTO;
DROP TABLE IF EXISTS RECETAS;
DROP TABLE IF EXISTS CITAS;
DROP TABLE IF EXISTS AGENDA_MEDICOS;
DROP TABLE IF EXISTS INVENTARIOS;
DROP TABLE IF EXISTS MEDICAMENTOS;
DROP TABLE IF EXISTS PACIENTE_PADECIMIENTO;
DROP TABLE IF EXISTS MEDICO_ESPECIALIDAD;
DROP TABLE IF EXISTS LABORATORIOS_CLINICOS;
DROP TABLE IF EXISTS FABRICANTES_MEDICAMENTOS;
DROP TABLE IF EXISTS FARMACIAS;
DROP TABLE IF EXISTS PADECIMIENTOS;
DROP TABLE IF EXISTS ESPECIALIDADES;
DROP TABLE IF EXISTS MEDICOS;
DROP TABLE IF EXISTS PACIENTES;
DROP TABLE IF EXISTS CLINICAS;
DROP TABLE IF EXISTS USUARIOS;

-- Reactivar validaciones de integridad referencial
SET FOREIGN_KEY_CHECKS = 1;
