# Generated by Django 4.2.30 on 2026-06-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=100)),
                ('num_ext', models.CharField(max_length=20)),
                ('num_int', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=100)),
                ('estado_ciudad', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'db_table': 'CLINICAS',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'ESPECIALIDADES',
            },
        ),
        migrations.CreateModel(
            name='LaboratorioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=100)),
                ('num_ext', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=100)),
                ('estado_ciudad', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Laboratorio Clínico',
                'verbose_name_plural': 'Laboratorios Clínicos',
                'db_table': 'LABORATORIOS_CLINICOS',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_profesional', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'MEDICOS',
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Especialidad de Médico',
                'verbose_name_plural': 'Especialidades de Médicos',
                'db_table': 'MEDICO_ESPECIALIDAD',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacim', models.DateField()),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('calle', models.CharField(max_length=100)),
                ('num_ext', models.CharField(max_length=20)),
                ('num_int', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(max_length=100)),
                ('alcaldia', models.CharField(max_length=100)),
                ('estado_ciudad', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=10)),
                ('nss', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'PACIENTES',
            },
        ),
        migrations.CreateModel(
            name='PacientePadecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Padecimiento de Paciente',
                'verbose_name_plural': 'Padecimientos de Pacientes',
                'db_table': 'PACIENTE_PADECIMIENTO',
            },
        ),
        migrations.CreateModel(
            name='Padecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('nombre_padecimiento', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Padecimiento',
                'verbose_name_plural': 'Padecimientos',
                'db_table': 'PADECIMIENTOS',
            },
        ),
    ]
