# Generated by Django 4.2.30 on 2026-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='num_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laboratorioclinico',
            name='num_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
