# Generated by Django 4.2.30 on 2026-06-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'MENSAJES',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('activa', models.BooleanField(default=True, help_text='Permite deshabilitar el chat cuando la cita concluye.')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'db_table': 'SALAS_CHAT',
            },
        ),
    ]
