# Generated by Django 4.2.30 on 2026-06-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Agenda Médica',
                'verbose_name_plural': 'Agendas Médicas',
                'db_table': 'AGENDA_MEDICOS',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('fecha_hora_timestamp', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('Agendada', 'Agendada'), ('Cancelada', 'Cancelada'), ('Atendida', 'Atendida')], default='Agendada', max_length=20)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'CITAS',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('fecha_emision', models.DateField()),
                ('indicaciones_generales', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'RECETAS',
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion_dias', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Recetas',
                'db_table': 'RECETA_MEDICAMENTO',
            },
        ),
        migrations.CreateModel(
            name='SolicitudEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='Indicador para el borrado lógico (Soft Delete)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta automatizada')),
                ('fecha_modif', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación automatizada')),
                ('tipo_estudio', models.CharField(max_length=150)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Solicitud de Estudio',
                'verbose_name_plural': 'Solicitudes de Estudio',
                'db_table': 'SOLICITUDES_ESTUDIO',
            },
        ),
    ]
