# Generated by Django 4.2.30 on 2026-06-29 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudestudio',
            name='laboratorio_clinico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nucleo.laboratorioclinico'),
        ),
    ]
